# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obraz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sciezka', models.FileField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('skrocona_tresc', models.CharField(blank=True, max_length=350)),
                ('tresc', models.TextField(blank=True)),
                ('haslo', models.CharField(blank=True, max_length=24)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('obrazek_postu', models.FileField(blank=True, null=True, upload_to=b'')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PosTagi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_postu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=24)),
            ],
        ),
        migrations.AddField(
            model_name='postagi',
            name='id_tagu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='Blog.Tag'),
        ),
    ]
